name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      
      - name: Install the plugin
        run: |
          python -m pip install -e tljh-voila-gallery

      - name: Check repo2docker is installed
        run: |
          python -m repo2docker --version
